vlog -work work C:/Users/AN515-56/Documents/Study/CE213.N11 HDL/Square root/simulation/modelsim/Datapath.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.Datapath_vlg_vec_tst
onerror {resume}
add wave {Datapath_vlg_vec_tst/i1/A}
add wave {Datapath_vlg_vec_tst/i1/A[15]}
add wave {Datapath_vlg_vec_tst/i1/A[14]}
add wave {Datapath_vlg_vec_tst/i1/A[13]}
add wave {Datapath_vlg_vec_tst/i1/A[12]}
add wave {Datapath_vlg_vec_tst/i1/A[11]}
add wave {Datapath_vlg_vec_tst/i1/A[10]}
add wave {Datapath_vlg_vec_tst/i1/A[9]}
add wave {Datapath_vlg_vec_tst/i1/A[8]}
add wave {Datapath_vlg_vec_tst/i1/A[7]}
add wave {Datapath_vlg_vec_tst/i1/A[6]}
add wave {Datapath_vlg_vec_tst/i1/A[5]}
add wave {Datapath_vlg_vec_tst/i1/A[4]}
add wave {Datapath_vlg_vec_tst/i1/A[3]}
add wave {Datapath_vlg_vec_tst/i1/A[2]}
add wave {Datapath_vlg_vec_tst/i1/A[1]}
add wave {Datapath_vlg_vec_tst/i1/A[0]}
add wave {Datapath_vlg_vec_tst/i1/B}
add wave {Datapath_vlg_vec_tst/i1/B[15]}
add wave {Datapath_vlg_vec_tst/i1/B[14]}
add wave {Datapath_vlg_vec_tst/i1/B[13]}
add wave {Datapath_vlg_vec_tst/i1/B[12]}
add wave {Datapath_vlg_vec_tst/i1/B[11]}
add wave {Datapath_vlg_vec_tst/i1/B[10]}
add wave {Datapath_vlg_vec_tst/i1/B[9]}
add wave {Datapath_vlg_vec_tst/i1/B[8]}
add wave {Datapath_vlg_vec_tst/i1/B[7]}
add wave {Datapath_vlg_vec_tst/i1/B[6]}
add wave {Datapath_vlg_vec_tst/i1/B[5]}
add wave {Datapath_vlg_vec_tst/i1/B[4]}
add wave {Datapath_vlg_vec_tst/i1/B[3]}
add wave {Datapath_vlg_vec_tst/i1/B[2]}
add wave {Datapath_vlg_vec_tst/i1/B[1]}
add wave {Datapath_vlg_vec_tst/i1/B[0]}
add wave {Datapath_vlg_vec_tst/i1/Clk}
add wave {Datapath_vlg_vec_tst/i1/O}
add wave {Datapath_vlg_vec_tst/i1/O[15]}
add wave {Datapath_vlg_vec_tst/i1/O[14]}
add wave {Datapath_vlg_vec_tst/i1/O[13]}
add wave {Datapath_vlg_vec_tst/i1/O[12]}
add wave {Datapath_vlg_vec_tst/i1/O[11]}
add wave {Datapath_vlg_vec_tst/i1/O[10]}
add wave {Datapath_vlg_vec_tst/i1/O[9]}
add wave {Datapath_vlg_vec_tst/i1/O[8]}
add wave {Datapath_vlg_vec_tst/i1/O[7]}
add wave {Datapath_vlg_vec_tst/i1/O[6]}
add wave {Datapath_vlg_vec_tst/i1/O[5]}
add wave {Datapath_vlg_vec_tst/i1/O[4]}
add wave {Datapath_vlg_vec_tst/i1/O[3]}
add wave {Datapath_vlg_vec_tst/i1/O[2]}
add wave {Datapath_vlg_vec_tst/i1/O[1]}
add wave {Datapath_vlg_vec_tst/i1/O[0]}
add wave {Datapath_vlg_vec_tst/i1/OE}
add wave {Datapath_vlg_vec_tst/i1/OE[11]}
add wave {Datapath_vlg_vec_tst/i1/OE[10]}
add wave {Datapath_vlg_vec_tst/i1/OE[9]}
add wave {Datapath_vlg_vec_tst/i1/OE[8]}
add wave {Datapath_vlg_vec_tst/i1/OE[7]}
add wave {Datapath_vlg_vec_tst/i1/OE[6]}
add wave {Datapath_vlg_vec_tst/i1/OE[5]}
add wave {Datapath_vlg_vec_tst/i1/OE[4]}
add wave {Datapath_vlg_vec_tst/i1/OE[3]}
add wave {Datapath_vlg_vec_tst/i1/OE[2]}
add wave {Datapath_vlg_vec_tst/i1/OE[1]}
add wave {Datapath_vlg_vec_tst/i1/OE[0]}
add wave {Datapath_vlg_vec_tst/i1/Op1}
add wave {Datapath_vlg_vec_tst/i1/Op1[1]}
add wave {Datapath_vlg_vec_tst/i1/Op1[0]}
add wave {Datapath_vlg_vec_tst/i1/Op2}
add wave {Datapath_vlg_vec_tst/i1/Op2[1]}
add wave {Datapath_vlg_vec_tst/i1/Op2[0]}
add wave {Datapath_vlg_vec_tst/i1/Load}
add wave {Datapath_vlg_vec_tst/i1/Load[4]}
add wave {Datapath_vlg_vec_tst/i1/Load[3]}
add wave {Datapath_vlg_vec_tst/i1/Load[2]}
add wave {Datapath_vlg_vec_tst/i1/Load[1]}
add wave {Datapath_vlg_vec_tst/i1/Load[0]}
add wave {Datapath_vlg_vec_tst/i1/AU1}
add wave {Datapath_vlg_vec_tst/i1/AU1[15]}
add wave {Datapath_vlg_vec_tst/i1/AU1[14]}
add wave {Datapath_vlg_vec_tst/i1/AU1[13]}
add wave {Datapath_vlg_vec_tst/i1/AU1[12]}
add wave {Datapath_vlg_vec_tst/i1/AU1[11]}
add wave {Datapath_vlg_vec_tst/i1/AU1[10]}
add wave {Datapath_vlg_vec_tst/i1/AU1[9]}
add wave {Datapath_vlg_vec_tst/i1/AU1[8]}
add wave {Datapath_vlg_vec_tst/i1/AU1[7]}
add wave {Datapath_vlg_vec_tst/i1/AU1[6]}
add wave {Datapath_vlg_vec_tst/i1/AU1[5]}
add wave {Datapath_vlg_vec_tst/i1/AU1[4]}
add wave {Datapath_vlg_vec_tst/i1/AU1[3]}
add wave {Datapath_vlg_vec_tst/i1/AU1[2]}
add wave {Datapath_vlg_vec_tst/i1/AU1[1]}
add wave {Datapath_vlg_vec_tst/i1/AU1[0]}
add wave {Datapath_vlg_vec_tst/i1/AU2}
add wave {Datapath_vlg_vec_tst/i1/AU2[15]}
add wave {Datapath_vlg_vec_tst/i1/AU2[14]}
add wave {Datapath_vlg_vec_tst/i1/AU2[13]}
add wave {Datapath_vlg_vec_tst/i1/AU2[12]}
add wave {Datapath_vlg_vec_tst/i1/AU2[11]}
add wave {Datapath_vlg_vec_tst/i1/AU2[10]}
add wave {Datapath_vlg_vec_tst/i1/AU2[9]}
add wave {Datapath_vlg_vec_tst/i1/AU2[8]}
add wave {Datapath_vlg_vec_tst/i1/AU2[7]}
add wave {Datapath_vlg_vec_tst/i1/AU2[6]}
add wave {Datapath_vlg_vec_tst/i1/AU2[5]}
add wave {Datapath_vlg_vec_tst/i1/AU2[4]}
add wave {Datapath_vlg_vec_tst/i1/AU2[3]}
add wave {Datapath_vlg_vec_tst/i1/AU2[2]}
add wave {Datapath_vlg_vec_tst/i1/AU2[1]}
add wave {Datapath_vlg_vec_tst/i1/AU2[0]}
add wave {Datapath_vlg_vec_tst/i1/R1}
add wave {Datapath_vlg_vec_tst/i1/R1[15]}
add wave {Datapath_vlg_vec_tst/i1/R1[14]}
add wave {Datapath_vlg_vec_tst/i1/R1[13]}
add wave {Datapath_vlg_vec_tst/i1/R1[12]}
add wave {Datapath_vlg_vec_tst/i1/R1[11]}
add wave {Datapath_vlg_vec_tst/i1/R1[10]}
add wave {Datapath_vlg_vec_tst/i1/R1[9]}
add wave {Datapath_vlg_vec_tst/i1/R1[8]}
add wave {Datapath_vlg_vec_tst/i1/R1[7]}
add wave {Datapath_vlg_vec_tst/i1/R1[6]}
add wave {Datapath_vlg_vec_tst/i1/R1[5]}
add wave {Datapath_vlg_vec_tst/i1/R1[4]}
add wave {Datapath_vlg_vec_tst/i1/R1[3]}
add wave {Datapath_vlg_vec_tst/i1/R1[2]}
add wave {Datapath_vlg_vec_tst/i1/R1[1]}
add wave {Datapath_vlg_vec_tst/i1/R1[0]}
add wave {Datapath_vlg_vec_tst/i1/R2}
add wave {Datapath_vlg_vec_tst/i1/R2[15]}
add wave {Datapath_vlg_vec_tst/i1/R2[14]}
add wave {Datapath_vlg_vec_tst/i1/R2[13]}
add wave {Datapath_vlg_vec_tst/i1/R2[12]}
add wave {Datapath_vlg_vec_tst/i1/R2[11]}
add wave {Datapath_vlg_vec_tst/i1/R2[10]}
add wave {Datapath_vlg_vec_tst/i1/R2[9]}
add wave {Datapath_vlg_vec_tst/i1/R2[8]}
add wave {Datapath_vlg_vec_tst/i1/R2[7]}
add wave {Datapath_vlg_vec_tst/i1/R2[6]}
add wave {Datapath_vlg_vec_tst/i1/R2[5]}
add wave {Datapath_vlg_vec_tst/i1/R2[4]}
add wave {Datapath_vlg_vec_tst/i1/R2[3]}
add wave {Datapath_vlg_vec_tst/i1/R2[2]}
add wave {Datapath_vlg_vec_tst/i1/R2[1]}
add wave {Datapath_vlg_vec_tst/i1/R2[0]}
add wave {Datapath_vlg_vec_tst/i1/R3}
add wave {Datapath_vlg_vec_tst/i1/R3[15]}
add wave {Datapath_vlg_vec_tst/i1/R3[14]}
add wave {Datapath_vlg_vec_tst/i1/R3[13]}
add wave {Datapath_vlg_vec_tst/i1/R3[12]}
add wave {Datapath_vlg_vec_tst/i1/R3[11]}
add wave {Datapath_vlg_vec_tst/i1/R3[10]}
add wave {Datapath_vlg_vec_tst/i1/R3[9]}
add wave {Datapath_vlg_vec_tst/i1/R3[8]}
add wave {Datapath_vlg_vec_tst/i1/R3[7]}
add wave {Datapath_vlg_vec_tst/i1/R3[6]}
add wave {Datapath_vlg_vec_tst/i1/R3[5]}
add wave {Datapath_vlg_vec_tst/i1/R3[4]}
add wave {Datapath_vlg_vec_tst/i1/R3[3]}
add wave {Datapath_vlg_vec_tst/i1/R3[2]}
add wave {Datapath_vlg_vec_tst/i1/R3[1]}
add wave {Datapath_vlg_vec_tst/i1/R3[0]}
add wave {Datapath_vlg_vec_tst/i1/R4}
add wave {Datapath_vlg_vec_tst/i1/R4[15]}
add wave {Datapath_vlg_vec_tst/i1/R4[14]}
add wave {Datapath_vlg_vec_tst/i1/R4[13]}
add wave {Datapath_vlg_vec_tst/i1/R4[12]}
add wave {Datapath_vlg_vec_tst/i1/R4[11]}
add wave {Datapath_vlg_vec_tst/i1/R4[10]}
add wave {Datapath_vlg_vec_tst/i1/R4[9]}
add wave {Datapath_vlg_vec_tst/i1/R4[8]}
add wave {Datapath_vlg_vec_tst/i1/R4[7]}
add wave {Datapath_vlg_vec_tst/i1/R4[6]}
add wave {Datapath_vlg_vec_tst/i1/R4[5]}
add wave {Datapath_vlg_vec_tst/i1/R4[4]}
add wave {Datapath_vlg_vec_tst/i1/R4[3]}
add wave {Datapath_vlg_vec_tst/i1/R4[2]}
add wave {Datapath_vlg_vec_tst/i1/R4[1]}
add wave {Datapath_vlg_vec_tst/i1/R4[0]}
add wave {Datapath_vlg_vec_tst/i1/R5}
add wave {Datapath_vlg_vec_tst/i1/R5[15]}
add wave {Datapath_vlg_vec_tst/i1/R5[14]}
add wave {Datapath_vlg_vec_tst/i1/R5[13]}
add wave {Datapath_vlg_vec_tst/i1/R5[12]}
add wave {Datapath_vlg_vec_tst/i1/R5[11]}
add wave {Datapath_vlg_vec_tst/i1/R5[10]}
add wave {Datapath_vlg_vec_tst/i1/R5[9]}
add wave {Datapath_vlg_vec_tst/i1/R5[8]}
add wave {Datapath_vlg_vec_tst/i1/R5[7]}
add wave {Datapath_vlg_vec_tst/i1/R5[6]}
add wave {Datapath_vlg_vec_tst/i1/R5[5]}
add wave {Datapath_vlg_vec_tst/i1/R5[4]}
add wave {Datapath_vlg_vec_tst/i1/R5[3]}
add wave {Datapath_vlg_vec_tst/i1/R5[2]}
add wave {Datapath_vlg_vec_tst/i1/R5[1]}
add wave {Datapath_vlg_vec_tst/i1/R5[0]}
add wave {Datapath_vlg_vec_tst/i1/S1}
add wave {Datapath_vlg_vec_tst/i1/S1[15]}
add wave {Datapath_vlg_vec_tst/i1/S1[14]}
add wave {Datapath_vlg_vec_tst/i1/S1[13]}
add wave {Datapath_vlg_vec_tst/i1/S1[12]}
add wave {Datapath_vlg_vec_tst/i1/S1[11]}
add wave {Datapath_vlg_vec_tst/i1/S1[10]}
add wave {Datapath_vlg_vec_tst/i1/S1[9]}
add wave {Datapath_vlg_vec_tst/i1/S1[8]}
add wave {Datapath_vlg_vec_tst/i1/S1[7]}
add wave {Datapath_vlg_vec_tst/i1/S1[6]}
add wave {Datapath_vlg_vec_tst/i1/S1[5]}
add wave {Datapath_vlg_vec_tst/i1/S1[4]}
add wave {Datapath_vlg_vec_tst/i1/S1[3]}
add wave {Datapath_vlg_vec_tst/i1/S1[2]}
add wave {Datapath_vlg_vec_tst/i1/S1[1]}
add wave {Datapath_vlg_vec_tst/i1/S1[0]}
add wave {Datapath_vlg_vec_tst/i1/S2}
add wave {Datapath_vlg_vec_tst/i1/S2[15]}
add wave {Datapath_vlg_vec_tst/i1/S2[14]}
add wave {Datapath_vlg_vec_tst/i1/S2[13]}
add wave {Datapath_vlg_vec_tst/i1/S2[12]}
add wave {Datapath_vlg_vec_tst/i1/S2[11]}
add wave {Datapath_vlg_vec_tst/i1/S2[10]}
add wave {Datapath_vlg_vec_tst/i1/S2[9]}
add wave {Datapath_vlg_vec_tst/i1/S2[8]}
add wave {Datapath_vlg_vec_tst/i1/S2[7]}
add wave {Datapath_vlg_vec_tst/i1/S2[6]}
add wave {Datapath_vlg_vec_tst/i1/S2[5]}
add wave {Datapath_vlg_vec_tst/i1/S2[4]}
add wave {Datapath_vlg_vec_tst/i1/S2[3]}
add wave {Datapath_vlg_vec_tst/i1/S2[2]}
add wave {Datapath_vlg_vec_tst/i1/S2[1]}
add wave {Datapath_vlg_vec_tst/i1/S2[0]}
run -all
